In [1]:
import pandas as pd

In [3]:
video = pd.read_json('dataset.json')

In [4]:
video.head()

,media,youtube_id,snippet,statistics,topicDetails,videos_information,language_information,bias,videos
0,"{'factual_reporting_label': 'HIGH', 'bias_labe...",UC4chaUevLgCVSz-RcgqgoZQ,"{'title': 'alliance4justice', 'description': '...","{'viewCount': 212274, 'subscriberCount': 288, ...","[Society, Politics]","{'videos_count': 50, 'video_ids': ['GMoawSfR-N...","{'lang_code': 'en', 'score': 1.0}",left,"[{'youtube_id': '3FUgm3STcDw', 'snippet': {'pu..."
1,"{'factual_reporting_label': 'HIGH', 'bias_labe...",UC5zlAAz2IxGSetD21mHy6sw,"{'title': 'Carbonated.TV', 'description': 'Car...","{'viewCount': 6865102, 'subscriberCount': 6734...","[Society, Politics]","{'videos_count': 876, 'video_ids': ['c5oXfGUhz...","{'lang_code': 'en', 'score': 1.0}",left,"[{'youtube_id': 'hIUqVueL56I', 'snippet': {'pu..."
2,"{'factual_reporting_label': 'MIXED', 'bias_lab...",UCAMOfF2PUYfKRLZuLATO1Tg,"{'title': 'Care2', 'description': 'Care2 is th...","{'viewCount': 102089, 'subscriberCount': 244, ...","[Society, Food, Lifestyle]","{'videos_count': 1, 'video_ids': ['LzilUKY7CEg']}","{'lang_code': 'en', 'score': 1.0}",left,"[{'youtube_id': 'LzilUKY7CEg', 'snippet': {'pu..."
3,"{'factual_reporting_label': 'HIGH', 'bias_labe...",UC0COu43Li7CUL2jseBpH9kQ,"{'title': 'seeprogress', 'description': 'Watch...","{'viewCount': 3906928, 'subscriberCount': 5765...","[Society, Politics]","{'videos_count': 552, 'video_ids': ['56puRLiol...","{'lang_code': 'en', 'score': 1.0}",left,"[{'youtube_id': 'XVrH9IxFFAw', 'snippet': {'pu..."
4,"{'factual_reporting_label': 'HIGH', 'bias_labe...",UC3Qs31jxhhi0tOMhSEpe3WQ,"{'title': 'PRWatch', 'description': 'The Cente...","{'viewCount': 488988, 'subscriberCount': 1269,...","[Society, Politics]","{'videos_count': 28, 'video_ids': ['Q0CaOhS7wJ...","{'lang_code': 'en', 'score': 1.0}",left,"[{'youtube_id': 'Q0CaOhS7wJg', 'snippet': {'pu..."

In [5]:
short = video[['snippet', 'videos_information', 'bias', 'youtube_id']]

In [48]:
short.head()

,snippet,videos_information,bias,youtube_id
0,"{'title': 'alliance4justice', 'description': '...","{'videos_count': 50, 'video_ids': ['GMoawSfR-N...",left,UC4chaUevLgCVSz-RcgqgoZQ
1,"{'title': 'Carbonated.TV', 'description': 'Car...","{'videos_count': 876, 'video_ids': ['c5oXfGUhz...",left,UC5zlAAz2IxGSetD21mHy6sw
2,"{'title': 'Care2', 'description': 'Care2 is th...","{'videos_count': 1, 'video_ids': ['LzilUKY7CEg']}",left,UCAMOfF2PUYfKRLZuLATO1Tg
3,"{'title': 'seeprogress', 'description': 'Watch...","{'videos_count': 552, 'video_ids': ['56puRLiol...",left,UC0COu43Li7CUL2jseBpH9kQ
4,"{'title': 'PRWatch', 'description': 'The Cente...","{'videos_count': 28, 'video_ids': ['Q0CaOhS7wJ...",left,UC3Qs31jxhhi0tOMhSEpe3WQ

In [28]:
short['videos_information'].iloc[0]

{'videos_count': 50,
 'video_ids': ['GMoawSfR-No',
  'TtvJU8vyrS8',
  '3FUgm3STcDw',
  'J5i2zl283IM',
  'DDhEvF_S1d4',
  'Eb-14VdeAN0',
  'TuKx87mYL7I',
  'E5mrpTAzIpc',
  'uWOUsqB8IPo',
  'oyi04gfpxMg',
  'QXtoZH6jJt4',
  'RdVTkaqAcBg',
  'JKMUkASXm38',
  '7BAYSBXHsu4',
  'Cjo_i7ebb1I',
  'R4fyH7sGDGs',
  '2cOt6lDA7P4',
  'udQnTxZZCLU',
  'MUHfte08WsQ',
  'e7pWcaxROmI',
  'wZHYlEabxNg',
  'CFYLfHgTOAA',
  'e6csnnk0uKM',
  'kRQmxKxAHQg',
  'zfGBHot_knY',
  'Le7obA1MGZY',
  '0mx0Fay8YpI',
  'almiXXPeO5U',
  'cJfBDTTMrdc',
  'XPPuJlmjmNY',
  '27YDCn57w2E',
  'Cp64is-lUIg',
  'cZRe9aU5e6E',
  'WJNOrmwFSD8',
  'DXXwNP2IbaM',
  'OIi0IIPq0To',
  'VS-Wf1hFbMQ',
  'b8LANN8bHC8',
  'yIDLAvJD9lg',
  '-MYEnPXOwb0',
  'WNDT-1Auebo',
  'FexehKcvwRs',
  'sAtoXwoHjYw',
  'G1M91y-m9a4',
  'u-LBJdyFFHs',
  'd8nuid91xU8',
  'PgTb6elOttQ',
  'fkDOBk2Yal4',
  'ezQ0Vwy8S5E',
  'fYYcyhx8cjY']}

In [11]:
import json

In [12]:
short.snippet

0      {'title': 'alliance4justice', 'description': '...
1      {'title': 'Carbonated.TV', 'description': 'Car...
2      {'title': 'Care2', 'description': 'Care2 is th...
3      {'title': 'seeprogress', 'description': 'Watch...
4      {'title': 'PRWatch', 'description': 'The Cente...
                             ...
416    {'title': 'Hillsdale College', 'description': ...
417    {'title': 'TheBlaze', 'description': 'Blaze Me...
418    {'title': 'TPPatriots', 'description': '', 'pu...
419    {'title': 'Police State - SNN', 'description':...
420    {'title': 'VDARE TV', 'description': 'Videos f...
Name: snippet, Length: 421, dtype: object

In [20]:
test1 = pd.DataFrame(list(short.snippet))

In [22]:
test1.head()

,title,description,publishedAt,country
0,alliance4justice,Alliance for Justice is a national associatio...,2010-08-30T19:20:44.000Z,NaN
1,Carbonated.TV,Carbonated.TV on YouTube showcases trending vi...,2009-10-07T17:21:15.000Z,US
2,Care2,Care2 is the world's largest community for goo...,2014-07-23T21:27:41.000Z,US
3,seeprogress,Watch videos produced by and/or featuring the ...,2006-05-17T15:42:43.000Z,NaN
4,PRWatch,The Center for Media and Democracy is a non-pr...,2007-03-09T23:54:31.000Z,NaN

In [25]:
test1['youtube_id'] = short.youtube_id

In [26]:
test1.head()

,title,description,publishedAt,country,youtube_id
0,alliance4justice,Alliance for Justice is a national associatio...,2010-08-30T19:20:44.000Z,NaN,UC4chaUevLgCVSz-RcgqgoZQ
1,Carbonated.TV,Carbonated.TV on YouTube showcases trending vi...,2009-10-07T17:21:15.000Z,US,UC5zlAAz2IxGSetD21mHy6sw
2,Care2,Care2 is the world's largest community for goo...,2014-07-23T21:27:41.000Z,US,UCAMOfF2PUYfKRLZuLATO1Tg
3,seeprogress,Watch videos produced by and/or featuring the ...,2006-05-17T15:42:43.000Z,NaN,UC0COu43Li7CUL2jseBpH9kQ
4,PRWatch,The Center for Media and Democracy is a non-pr...,2007-03-09T23:54:31.000Z,NaN,UC3Qs31jxhhi0tOMhSEpe3WQ

In [38]:
test2 = pd.DataFrame(list(short.videos_information))
test2['youtube_id'] = short.youtube_id
test2 = test2.drop(['videos_count'], axis = 1)

In [39]:
test2.head()

                                           video_ids                youtube_id
0  [GMoawSfR-No, TtvJU8vyrS8, 3FUgm3STcDw, J5i2zl...  UC4chaUevLgCVSz-RcgqgoZQ
1  [c5oXfGUhzgA, 15BkzBSj1eA, zABlzV39mlM, GX57qK...  UC5zlAAz2IxGSetD21mHy6sw
2                                      [LzilUKY7CEg]  UCAMOfF2PUYfKRLZuLATO1Tg
3  [56puRLiolUk, bW69WfcEmJc, XVrH9IxFFAw, va-NMk...  UC0COu43Li7CUL2jseBpH9kQ
4  [Q0CaOhS7wJg, cniJXp3rO-Q, KNlz_rz9cQY, WIlogR...  UC3Qs31jxhhi0tOMhSEpe3WQ

In [43]:
test21 = test2.groupby('youtube_id')['video_ids'].apply(lambda x: pd.DataFrame(x.iloc[0], columns = ['video_id'])).reset_index()

In [44]:

test21.head()

                 youtube_id  level_1     video_id
0  UC-5fbO9oT3SKREKe2pBFK8A        0  CqY18K8ONwA
1  UC-5fbO9oT3SKREKe2pBFK8A        1  BcmDb_91FEw
2  UC-5fbO9oT3SKREKe2pBFK8A        2  7tBbjcpDaDs
3  UC-5fbO9oT3SKREKe2pBFK8A        3  ljSvLseJrcc
4  UC-5fbO9oT3SKREKe2pBFK8A        4  ysf8eVLJ0Jw

In [45]:
test21 = test21.drop(['level_1'], axis = 1)

In [46]:
test21.head()

                 youtube_id     video_id
0  UC-5fbO9oT3SKREKe2pBFK8A  CqY18K8ONwA
1  UC-5fbO9oT3SKREKe2pBFK8A  BcmDb_91FEw
2  UC-5fbO9oT3SKREKe2pBFK8A  7tBbjcpDaDs
3  UC-5fbO9oT3SKREKe2pBFK8A  ljSvLseJrcc
4  UC-5fbO9oT3SKREKe2pBFK8A  ysf8eVLJ0Jw

In [51]:
test3 = pd.DataFrame(list(short.bias))
test3.head()

      0
0  left
1  left
2  left
3  left
4  left

In [55]:
test1['bias'] = short.bias

In [56]:
test1.head()

,title,description,publishedAt,country,youtube_id,videos_information,bias
0,alliance4justice,Alliance for Justice is a national associatio...,2010-08-30T19:20:44.000Z,NaN,UC4chaUevLgCVSz-RcgqgoZQ,UC4chaUevLgCVSz-RcgqgoZQ,left
1,Carbonated.TV,Carbonated.TV on YouTube showcases trending vi...,2009-10-07T17:21:15.000Z,US,UC5zlAAz2IxGSetD21mHy6sw,UC5zlAAz2IxGSetD21mHy6sw,left
2,Care2,Care2 is the world's largest community for goo...,2014-07-23T21:27:41.000Z,US,UCAMOfF2PUYfKRLZuLATO1Tg,UCAMOfF2PUYfKRLZuLATO1Tg,left
3,seeprogress,Watch videos produced by and/or featuring the ...,2006-05-17T15:42:43.000Z,NaN,UC0COu43Li7CUL2jseBpH9kQ,UC0COu43Li7CUL2jseBpH9kQ,left
4,PRWatch,The Center for Media and Democracy is a non-pr...,2007-03-09T23:54:31.000Z,NaN,UC3Qs31jxhhi0tOMhSEpe3WQ,UC3Qs31jxhhi0tOMhSEpe3WQ,left